Fix Error: The `add-path` command is disabled
Error: Unable to process command '::add-path::/home/runner/work/tutorials/tutorials/bin'
successfully.
Error: The `add-path` command is disabled.
Please upgrade to using Environment Files or opt into unsecure command execution by setting
the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/